ifndef KILIX_TOP_DOWN_DIR
KILIX_TOP_DOWN_DIR := third_party/kilix-top-down-engine
endif

KILIX_TOP_DOWN_ROOT := $(abspath $(KILIX_TOP_DOWN_DIR))
KILIX_TOP_DOWN_BUILD_DIR ?= $(KILIX_TOP_DOWN_ROOT)/build
KILIX_TOP_DOWN_BUILD_ROOT := $(abspath $(KILIX_TOP_DOWN_BUILD_DIR))
ifneq ($(strip $(SOFT_RASTER_DIR)),)
KILIX_TD_SOFT_RASTER_ROOT := $(abspath $(SOFT_RASTER_DIR))
else
KILIX_TD_SOFT_RASTER_ROOT := $(KILIX_TOP_DOWN_ROOT)/third_party/soft-raster
endif

KILIX_TD_CORE_LIB := $(KILIX_TOP_DOWN_BUILD_ROOT)/libkilix-top-down-core.a
KILIX_TD_SOFT_LIB := $(KILIX_TOP_DOWN_BUILD_ROOT)/libkilix-top-down-soft.a
KILIX_TD_LIBS := $(KILIX_TD_SOFT_LIB) $(KILIX_TD_CORE_LIB)
KILIX_TD_CPPFLAGS := -I$(KILIX_TOP_DOWN_ROOT)/include
KILIX_TD_PUBLIC_HEADERS := $(wildcard $(KILIX_TOP_DOWN_ROOT)/include/*.h)
KILIX_TD_CORE_INPUTS := $(KILIX_TOP_DOWN_ROOT)/src/view.c \
	$(KILIX_TOP_DOWN_ROOT)/include/kilix_top_down_types.h \
	$(KILIX_TOP_DOWN_ROOT)/include/kilix_top_down_view.h \
	$(KILIX_TOP_DOWN_ROOT)/Makefile
KILIX_TD_SOFT_INPUTS := $(KILIX_TOP_DOWN_ROOT)/src/soft.c \
	$(KILIX_TD_PUBLIC_HEADERS) \
	$(KILIX_TD_SOFT_RASTER_ROOT)/include/soft_raster.h \
	$(KILIX_TOP_DOWN_ROOT)/Makefile

$(KILIX_TD_CORE_LIB): $(KILIX_TD_CORE_INPUTS)
	$(MAKE) -C $(KILIX_TOP_DOWN_ROOT) \
		BUILD_DIR="$(KILIX_TOP_DOWN_BUILD_ROOT)" \
		SOFT_RASTER_DIR="$(KILIX_TD_SOFT_RASTER_ROOT)" "$@"

$(KILIX_TD_SOFT_LIB): $(KILIX_TD_CORE_LIB) $(KILIX_TD_SOFT_INPUTS)
	$(MAKE) -C $(KILIX_TOP_DOWN_ROOT) \
		BUILD_DIR="$(KILIX_TOP_DOWN_BUILD_ROOT)" \
		SOFT_RASTER_DIR="$(KILIX_TD_SOFT_RASTER_ROOT)" "$@"
